# Generated by Django 5.0.6 on 2024-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('family', 'Family'), ('hobbies', 'Hobbies'), ('education', 'Education'), ('entertainment', 'Entertainment')], default='work', max_length=50),
            preserve_default=False,
        ),
    ]
